export enum Action {
  AUTH_SIGN_UP = "AUTH_SIGN_UP",
  AUTH_SIGN_IN = "AUTH_SIGN_IN",
  AUTH_LOGOUT = "AUTH_LOGOUT",
  AUTH_CHECK = "AUTH_CHECK",
  ADD_ITEM = "ADD_ITEM",
  REMOVE_ITEM = "REMOVE_ITEM",
  CLEAR_CART = "CLEAR_CART",
}
