const router = require("express").Router();
const authRouter = require("./auth/auth.routes");
const categoriesRouter = require("./categories/categories.routes");
const postsRouter = require("./posts/posts.routes");
const likesRouter = require("./posts/likes.routes");
const favoritesRouter = require("./posts/favorites.routes");
const harmRouter = require("./posts/harmFormula.routes");
const cartRouter = require("./api/cart.api.routes");
const materialsRouter = require("./materials/materials.routes");
const userRouter = require("./user/user.routes");
router.use("/api/auth", authRouter);
router.use("/api/categories", categoriesRouter);
router.use("/api/posts", postsRouter);
router.use("/api/categories/:categoryId/posts", likesRouter);
router.use("/api/favorites", favoritesRouter);
router.use("/api/harm", harmRouter);
router.use("/api/cart", cartRouter);
router.use("/api/materials", materialsRouter);
router.use("/api/user", userRouter);

module.exports = router;
