"use strict";

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert(
      "Posts",
      [
        {
          name: "Подкатегория 1_1",
          price: "1000",
          description: "Вай какие линзы",
          image:
            "https://static.cdn.oskelly.ru/product/1793650/tiny-dcec2a97-c84b-4b7e-b1ff-1165682fffaa.jpg.webp",
          size: "23",
          publich: true,
          weight: "100",
          user_id: 1,
          category_id: 1,
          sub_category_id: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Подкатегория 1_2",
          price: "10",
          description: "Фу очки",
          image:
            "https://static.cdn.oskelly.ru/product/1794161/tiny-0ae4fc36-1f65-4791-96d0-fa3fdafc7b0c.jpg.webp",
          size: "26",
          publich: true,
          weight: "100",
          user_id: 1,
          category_id: 1,
          sub_category_id: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Подкатегория 1_3",
          price: "10",
          description: "Фу очки",
          image:
            "https://static.cdn.oskelly.ru/product/1794161/tiny-0ae4fc36-1f65-4791-96d0-fa3fdafc7b0c.jpg.webp",
          size: "26",
          publich: true,
          weight: "100",
          user_id: 1,
          category_id: 1,
          sub_category_id: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Подкатегория 1_4",
          price: "10",
          description: "Фу очки",
          image:
            "https://static.cdn.oskelly.ru/product/1794161/tiny-0ae4fc36-1f65-4791-96d0-fa3fdafc7b0c.jpg.webp",
          size: "26",
          publich: true,
          weight: "100",
          user_id: 1,
          category_id: 1,
          sub_category_id: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Подкатегория 1_5",
          price: "10",
          description: "Фу очки",
          image:
            "https://static.cdn.oskelly.ru/product/1794161/tiny-0ae4fc36-1f65-4791-96d0-fa3fdafc7b0c.jpg.webp",
          size: "26",
          publich: true,
          weight: "100",
          user_id: 1,
          category_id: 1,
          sub_category_id: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Подкатегория 2_1",
          price: "10",
          description: "Фу очки",
          image:
            "https://static.cdn.oskelly.ru/product/1794161/tiny-0ae4fc36-1f65-4791-96d0-fa3fdafc7b0c.jpg.webp",
          size: "26",
          publich: true,
          weight: "100",
          user_id: 1,
          category_id: 2,
          sub_category_id: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Подкатегория 2_2",
          price: "10",
          description: "Фу очки",
          image:
            "https://static.cdn.oskelly.ru/product/1794161/tiny-0ae4fc36-1f65-4791-96d0-fa3fdafc7b0c.jpg.webp",
          size: "26",
          publich: true,
          weight: "100",
          user_id: 1,
          category_id: 2,
          sub_category_id: 7,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Подкатегория 2_3",
          price: "10",
          description: "Фу очки",
          image:
            "https://static.cdn.oskelly.ru/product/1794161/tiny-0ae4fc36-1f65-4791-96d0-fa3fdafc7b0c.jpg.webp",
          size: "26",
          publich: true,
          weight: "100",
          user_id: 1,
          category_id: 2,
          sub_category_id: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Подкатегория 2_4",
          price: "10",
          description: "Фу очки",
          image:
            "https://static.cdn.oskelly.ru/product/1794161/tiny-0ae4fc36-1f65-4791-96d0-fa3fdafc7b0c.jpg.webp",
          size: "26",
          publich: true,
          weight: "100",
          user_id: 1,
          category_id: 2,
          sub_category_id: 9,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Подкатегория 2_5",
          price: "10",
          description: "Фу очки",
          image:
            "https://static.cdn.oskelly.ru/product/1794161/tiny-0ae4fc36-1f65-4791-96d0-fa3fdafc7b0c.jpg.webp",
          size: "26",
          publich: true,
          weight: "100",
          user_id: 1,
          category_id: 2,
          sub_category_id: 10,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Подкатегория 2_6",
          price: "10",
          description: "Фу очки",
          image:
            "https://static.cdn.oskelly.ru/product/1794161/tiny-0ae4fc36-1f65-4791-96d0-fa3fdafc7b0c.jpg.webp",
          size: "26",
          publich: true,
          weight: "100",
          user_id: 1,
          category_id: 2,
          sub_category_id: 11,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Подкатегория 2_7",
          price: "10",
          description: "Фу очки",
          image:
            "https://static.cdn.oskelly.ru/product/1794161/tiny-0ae4fc36-1f65-4791-96d0-fa3fdafc7b0c.jpg.webp",
          size: "26",
          publich: true,
          weight: "100",
          user_id: 1,
          category_id: 2,
          sub_category_id: 12,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Подкатегория 2_8",
          price: "10",
          description: "Фу очки",
          image:
            "https://static.cdn.oskelly.ru/product/1794161/tiny-0ae4fc36-1f65-4791-96d0-fa3fdafc7b0c.jpg.webp",
          size: "26",
          publich: true,
          weight: "100",
          user_id: 1,
          category_id: 2,
          sub_category_id: 13,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Подкатегория 2_9",
          price: "10",
          description: "Фу очки",
          image:
            "https://static.cdn.oskelly.ru/product/1794161/tiny-0ae4fc36-1f65-4791-96d0-fa3fdafc7b0c.jpg.webp",
          size: "26",
          publich: true,
          weight: "100",
          user_id: 1,
          category_id: 2,
          sub_category_id: 14,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Подкатегория 3_1",
          price: "10",
          description: "Фу очки",
          image:
            "https://static.cdn.oskelly.ru/product/1794161/tiny-0ae4fc36-1f65-4791-96d0-fa3fdafc7b0c.jpg.webp",
          size: "26",
          publich: true,
          weight: "100",
          user_id: 1,
          category_id: 3,
          sub_category_id: 15,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Подкатегория 3_1",
          price: "10",
          description: "Фу очки",
          image:
            "https://static.cdn.oskelly.ru/product/1794161/tiny-0ae4fc36-1f65-4791-96d0-fa3fdafc7b0c.jpg.webp",
          size: "26",
          publich: true,
          weight: "100",
          user_id: 1,
          category_id: 3,
          sub_category_id: 16,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Подкатегория 3_2",
          price: "10",
          description: "Фу очки",
          image:
            "https://static.cdn.oskelly.ru/product/1794161/tiny-0ae4fc36-1f65-4791-96d0-fa3fdafc7b0c.jpg.webp",
          size: "26",
          publich: true,
          weight: "100",
          user_id: 1,
          category_id: 3,
          sub_category_id: 17,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Подкатегория 3_3",
          price: "10",
          description: "Фу очки",
          image:
            "https://static.cdn.oskelly.ru/product/1794161/tiny-0ae4fc36-1f65-4791-96d0-fa3fdafc7b0c.jpg.webp",
          size: "26",
          publich: true,
          weight: "100",
          user_id: 1,
          category_id: 3,
          sub_category_id: 18,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Подкатегория 3_4",
          price: "10",
          description: "Фу очки",
          image:
            "https://static.cdn.oskelly.ru/product/1794161/tiny-0ae4fc36-1f65-4791-96d0-fa3fdafc7b0c.jpg.webp",
          size: "26",
          publich: true,
          weight: "100",
          user_id: 1,
          category_id: 3,
          sub_category_id: 19,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Подкатегория 3_5",
          price: "10",
          description: "Фу очки",
          image:
            "https://static.cdn.oskelly.ru/product/1794161/tiny-0ae4fc36-1f65-4791-96d0-fa3fdafc7b0c.jpg.webp",
          size: "26",
          publich: true,
          weight: "100",
          user_id: 1,
          category_id: 3,
          sub_category_id: 20,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Подкатегория 4_1",
          price: "10",
          description: "Фу очки",
          image:
            "https://static.cdn.oskelly.ru/product/1794161/tiny-0ae4fc36-1f65-4791-96d0-fa3fdafc7b0c.jpg.webp",
          size: "26",
          publich: true,
          weight: "100",
          user_id: 1,
          category_id: 4,
          sub_category_id: 21,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Подкатегория 4_2",
          price: "10",
          description: "Фу очки",
          image:
            "https://static.cdn.oskelly.ru/product/1794161/tiny-0ae4fc36-1f65-4791-96d0-fa3fdafc7b0c.jpg.webp",
          size: "26",
          publich: true,
          weight: "100",
          user_id: 1,
          category_id: 4,
          sub_category_id: 22,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Подкатегория 4_3",
          price: "10",
          description: "Фу очки",
          image:
            "https://static.cdn.oskelly.ru/product/1794161/tiny-0ae4fc36-1f65-4791-96d0-fa3fdafc7b0c.jpg.webp",
          size: "26",
          publich: true,
          weight: "100",
          user_id: 1,
          category_id: 4,
          sub_category_id: 23,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Подкатегория 4_4",
          price: "10",
          description: "Фу очки",
          image:
            "https://static.cdn.oskelly.ru/product/1794161/tiny-0ae4fc36-1f65-4791-96d0-fa3fdafc7b0c.jpg.webp",
          size: "26",
          publich: true,
          weight: "100",
          user_id: 1,
          category_id: 4,
          sub_category_id: 24,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Подкатегория 5_1",
          price: "10",
          description: "Фу очки",
          image:
            "https://static.cdn.oskelly.ru/product/1794161/tiny-0ae4fc36-1f65-4791-96d0-fa3fdafc7b0c.jpg.webp",
          size: "26",
          publich: true,
          weight: "100",
          user_id: 1,
          category_id: 5,
          sub_category_id: 25,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Подкатегория 5_2",
          price: "10",
          description: "Фу очки",
          image:
            "https://static.cdn.oskelly.ru/product/1794161/tiny-0ae4fc36-1f65-4791-96d0-fa3fdafc7b0c.jpg.webp",
          size: "26",
          publich: true,
          weight: "100",
          user_id: 1,
          category_id: 5,
          sub_category_id: 26,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Подкатегория 5_3",
          price: "10",
          description: "Фу очки",
          image:
            "https://static.cdn.oskelly.ru/product/1794161/tiny-0ae4fc36-1f65-4791-96d0-fa3fdafc7b0c.jpg.webp",
          size: "26",
          publich: true,
          weight: "100",
          user_id: 1,
          category_id: 5,
          sub_category_id: 27,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Подкатегория 5_4",
          price: "10",
          description: "Фу очки",
          image:
            "https://static.cdn.oskelly.ru/product/1794161/tiny-0ae4fc36-1f65-4791-96d0-fa3fdafc7b0c.jpg.webp",
          size: "26",
          publich: true,
          weight: "100",
          user_id: 1,
          category_id: 5,
          sub_category_id: 28,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Подкатегория 6_1",
          price: "10",
          description: "Фу очки",
          image:
            "https://static.cdn.oskelly.ru/product/1794161/tiny-0ae4fc36-1f65-4791-96d0-fa3fdafc7b0c.jpg.webp",
          size: "26",
          publich: true,
          weight: "100",
          user_id: 1,
          category_id: 6,
          sub_category_id: 29,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Подкатегория 6_2",
          price: "10",
          description: "Фу очки",
          image:
            "https://static.cdn.oskelly.ru/product/1794161/tiny-0ae4fc36-1f65-4791-96d0-fa3fdafc7b0c.jpg.webp",
          size: "26",
          publich: true,
          weight: "100",
          user_id: 1,
          category_id: 6,
          sub_category_id: 30,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Подкатегория 6_3",
          price: "10",
          description: "Фу очки",
          image:
            "https://static.cdn.oskelly.ru/product/1794161/tiny-0ae4fc36-1f65-4791-96d0-fa3fdafc7b0c.jpg.webp",
          size: "26",
          publich: true,
          weight: "100",
          user_id: 1,
          category_id: 6,
          sub_category_id: 31,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Подкатегория 6_4",
          price: "10",
          description: "Фу очки",
          image:
            "https://static.cdn.oskelly.ru/product/1794161/tiny-0ae4fc36-1f65-4791-96d0-fa3fdafc7b0c.jpg.webp",
          size: "26",
          publich: true,
          weight: "100",
          user_id: 1,
          category_id: 6,
          sub_category_id: 32,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Подкатегория 6_5",
          price: "10",
          description: "Фу очки",
          image:
            "https://static.cdn.oskelly.ru/product/1794161/tiny-0ae4fc36-1f65-4791-96d0-fa3fdafc7b0c.jpg.webp",
          size: "26",
          publich: true,
          weight: "100",
          user_id: 1,
          category_id: 6,
          sub_category_id: 33,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      {}
    );
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete("Posts", null, {});
  },
};
