"use strict";

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert(
      "Posts",
      [
        {
          name: "GENTLE MONSTER",
          price: "10000",
          description:
            "Очки новые , не носились . цвет стекло розовый прозрачный очень стильные .",
          image:
            "https://static.cdn.oskelly.ru/product/1745357/tiny-abb47a38-7085-4159-924b-786466090788.jpg.webp",
          size: "25 см",
          publich: true,
          weight: "300",
          user_id: 1,
          category_id: 1,
          sub_category_id: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "JIMMY CHOO",
          price: "15000",
          description:
            "Солнцезащитные очки Jimmy Choo, Italy Покупала в Слепая Курица, г.Москва Состояние отличное, носились редко, 2-3 выхода Коробка, салфетка Цвет серый-черный, плавный переход Перламутр на дужках",
          image:
            "https://static.cdn.oskelly.ru/product/1425265/tiny-1c894198-1e0b-41ca-a446-62948203d618.jpg.webp",
          size: "25 см ",
          publich: true,
          weight: "350",
          user_id: 1,
          category_id: 1,
          sub_category_id: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "VALENTINO",
          price: "9500",
          description:
            "Очки авиаторы Valentino, полный комплект бутика. Два чехла, коробка, все карточки и штрихкоды. Градиент черный. Шикарнейшие, форма идет практически всем. Состояние отличное, из нюансов на стеклах есть несколько микро царапин от неправильного хранения, абсолютно незаметные в носке. Очки от силы надевались раз 5, в остальном никаких нюансов и недочетов нет",
          image:
            "https://static.cdn.oskelly.ru/product/1805847/tiny-f7cfbec9-2be4-47bb-ac5e-230dcc1cd057.jpg.webp",
          size: "25 см",
          publich: true,
          weight: "450",
          user_id: 1,
          category_id: 1,
          sub_category_id: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "FURLA",
          price: "13000",
          description:
            "Производство: Италия 🇮🇹. Комплект: оправа, салфетка для протирания линз, футляр. Легкая, стильная, универсальная, качественная оправа.",
          image:
            "https://static.cdn.oskelly.ru/product/1805590/item-1949ee4a-0a2b-42c2-8441-746a5e0503fe.jpg.webp",
          size: "25 см",
          publich: true,
          weight: "200",
          user_id: 1,
          category_id: 1,
          sub_category_id: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "RAY BAN",
          price: "11000",
          description:
            "Солнцезащитные очки Ray-Ban Wayfarer из золотистого металла с градиентными линзами. В комплекте чехол и пыльник. Состояние отличное Детали: Незначительные потертости; небольшая царапина на линзе. Следы хранения и носки.",
          image:
            "https://static.cdn.oskelly.ru/product/1039234/tiny-ee46a17b-9adc-4533-ae1b-a3acd6cdb18a.webp.webp",
          size: "25 см",
          publich: true,
          weight: "100",
          user_id: 1,
          category_id: 1,
          sub_category_id: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "ZILLI",
          price: "25000",
          description:
            "Светло-коричневый ремень из кожи страуса с золотой пряжкой. Маркировка 44 (110 см). В идеальном состоянии, носился с удовольствием, но, к сожалению, больше не хватает охвата",
          image:
            "https://static.cdn.oskelly.ru/product/1709991/item-e7226c83-3990-4dc5-9dcd-4f9d7a687474.jpg.webp",
          size: "110 см",
          publich: true,
          weight: "350",
          user_id: 1,
          category_id: 1,
          sub_category_id: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "ARTIOLI",
          price: "26000",
          description: "Новый ремень",
          image:
            "https://static.cdn.oskelly.ru/product/1783383/item-62d8a583-5154-4336-95f5-dd570fd5002d.jpg.webp",
          size: "90 см",
          publich: true,
          weight: "500",
          user_id: 1,
          category_id: 1,
          sub_category_id: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "BALENCIAGA ",
          price: "65000",
          description:
            "Ремень BALENCIAGA в отличном состоянии, без дефектов, в комплекте пыльник,",
          image:
            "https://static.cdn.oskelly.ru/product/1807534/item-56740772-d7a0-4384-9109-eff81c0e2962.jpg.webp",
          size: "85 см",
          publich: true,
          weight: "250",
          user_id: 1,
          category_id: 1,
          sub_category_id: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "NO.21",
          price: "10000",
          description: "Эластичный пояс с застёжкой на пряжку.",
          image:
            "https://static.cdn.oskelly.ru/product/996308/item-49b0b527-4af0-41b0-909c-ddf5feea371c.png.webp",
          size: "63-90 см",
          publich: true,
          weight: "150",
          user_id: 1,
          category_id: 1,
          sub_category_id: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "SAINT LAURENT",
          price: "30000",
          description: "Модель молочного цвета, размер ремня ",
          image:
            "https://static.cdn.oskelly.ru/product/1806903/item-4aeee286-5190-4711-b11d-c2d92aa2f973.jpg.webp",
          size: "85 см",
          publich: true,
          weight: "250",
          user_id: 1,
          category_id: 1,
          sub_category_id: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Ami",
          price: "15000",
          description: "Перчатки Ami Paris из роскошно мягкой шерстяной пряжи",
          image:
            "https://static.cdn.oskelly.ru/product/1581806/item-9df5fd86-d406-4be6-862f-5dc652519dda.jpg.webp",
          size: "25.5 см",
          publich: true,
          weight: "100",
          user_id: 1,
          category_id: 1,
          sub_category_id: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "GIORGIO ARMANI",
          price: "20500",
          description:
            "Модель с фактурной вязкой в технике английской резинки, широкой эластичной манжетой, нашивкой с логотипом.",
          image:
            "https://static.cdn.oskelly.ru/product/1667136/item-ddf06483-4a77-4231-9bb2-06afb19d279f.webp",
          size: "26 см",
          publich: true,
          weight: "150",
          user_id: 1,
          category_id: 1,
          sub_category_id: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Dunhill",
          price: "16500",
          description: "Перчатки Dunhill",
          image:
            "https://static.cdn.oskelly.ru/product/1304885/item-d570c053-031e-4514-b76a-ec628414662a.jpg.webp",
          size: "25 см",
          publich: true,
          weight: "200",
          user_id: 1,
          category_id: 1,
          sub_category_id: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Max Mara",
          price: "13000",
          description: "Перчатки Max Mara из кожи ягнёнка, ",
          image:
            "https://static.cdn.oskelly.ru/product/1379957/item-9293bfd1-b13e-48ff-9fe3-0d47eed129b0.jpg.webp",
          size: "38 см",
          publich: true,
          weight: "170",
          user_id: 1,
          category_id: 1,
          sub_category_id: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Belstaff",
          price: "12000",
          description:
            "Belstaff новые перчатки. Роскошный подарок. Очень красивый цвет. Производство Италия , потрясающая выделка кожи и качество бренда как всегда на высоте",
          image:
            "https://static.cdn.oskelly.ru/product/1423903/item-df14bd88-e0c8-4524-a2d1-d79689b22ef8.JPG.webp",
          size: "M",
          publich: true,
          weight: "130",
          user_id: 1,
          category_id: 1,
          sub_category_id: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "HERMES PRE-OWNED",
          price: "7500",
          description: "Мужской шарф из новой коллекции",
          image:
            "https://static.cdn.oskelly.ru/product/1805622/item-32d1e814-ab71-4994-86d9-f430ad0ec951.jpg.webp",
          size: "25x125 см",
          publich: true,
          weight: "100",
          user_id: 1,
          category_id: 1,
          sub_category_id: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Burberry",
          price: "11000",
          description: "Burberry шарф состояние отличное",
          image:
            "https://static.cdn.oskelly.ru/product/1484681/item-3660b6e9-ab79-4594-ae3d-e41afde61bff.png.webp",
          size: "29x170 см",
          publich: true,
          weight: "110",
          user_id: 1,
          category_id: 1,
          sub_category_id: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Acne Studios",
          price: "28000",
          description:
            "Модель украшена вышитым логотипом Acne Studios. Изготовлен из тщательно отобранного материала",
          image:
            "https://static.cdn.oskelly.ru/product/1807335/item-f6641b88-b165-4ad3-9adb-8e2f24a8a116.jpg.webp",
          size: "29x180 см",
          publich: true,
          weight: "105",
          user_id: 1,
          category_id: 1,
          sub_category_id: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "LOEWE",
          price: "12000",
          description: "Красивый шарф",
          image:
            "https://static.cdn.oskelly.ru/product/1751292/item-d197af05-f68f-4809-a92d-685ff98f46d0.jpg.webp",
          size: "25x210 см",
          publich: true,
          weight: "200",
          user_id: 1,
          category_id: 1,
          sub_category_id: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "ALEXANDER MCQUEEN",
          price: "25000",
          description:
            "Легкий шерстяной шарф с принтом в виде черепа по всей длине и подписью Александра Маккуина внизу. Отделка с обтрепанными краями.",
          image:
            "https://static.cdn.oskelly.ru/product/1759857/item-552e02c8-2a4d-4d38-b9fc-caf66b1ac50d.webp",
          size: "26x180 см",
          publich: true,
          weight: "100",
          user_id: 1,
          category_id: 1,
          sub_category_id: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "STUSSY",
          price: "5700",
          description: "Stussy Снэпбэк кепка os состояние отличное",
          image:
            "https://static.cdn.oskelly.ru/product/902868/item-0d303c40-0f33-4cf7-a2ba-bae7eb2c00b4.jpg.webp",
          size: "54-60",
          publich: true,
          weight: "250",
          user_id: 1,
          category_id: 1,
          sub_category_id: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "SVEVO",
          price: "40000",
          description: "100% нежный и приятный в носке кашемир",
          image:
            "https://static.cdn.oskelly.ru/product/1037986/item-ced5cbe2-fee3-4c6f-afce-97d9f899fee9.jpg.webp",
          size: "54-60",
          publich: true,
          weight: "280",
          user_id: 1,
          category_id: 1,
          sub_category_id: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "EMPORIO ARMANI",
          price: "13000",
          description:
            "Шапка в небесно-голубом оттенке сохранит тепло и лёгкость зимнего образа",
          image:
            "https://static.cdn.oskelly.ru/product/1794161/tiny-0ae4fc36-1f65-4791-96d0-fa3fdafc7b0c.jpg.webp",
          size: "L",
          publich: true,
          weight: "300",
          user_id: 1,
          category_id: 1,
          sub_category_id: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "NANUSHKA",
          price: "35000",
          description:
            "Пальто кроя оверсайз выигрышно преподнесет хрупкость фигуры, играя на контрасте. Строгость рубашечного стиля здесь также компенсируется расслабленностью подачи, поэтому модель окажется уместной ко многим образам, как к деловым, так к неформальным.",
          image:
            "https://static.cdn.oskelly.ru/product/1794161/tiny-0ae4fc36-1f65-4791-96d0-fa3fdafc7b0c.jpg.webp",
          size: "XS",
          publich: true,
          weight: "1500",
          user_id: 1,
          category_id: 2,
          sub_category_id: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "PINKO",
          price: "18000",
          description:
            "Дизайнеры PINKO любят создавать одежду силуэта oversize. Не стала исключением и утепленная угольно-черная джинсовая куртка-рубашка из новой коллекции.",
          image:
            "https://static.cdn.oskelly.ru/product/1530008/item-67692e87-51f4-4ea5-aeda-e01aa8d5fef3.webp",
          size: "XS",
          publich: true,
          weight: "1200",
          user_id: 1,
          category_id: 2,
          sub_category_id: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "CORTIGIANI",
          price: "240000",
          description: "Куртка CORTIGIANI",
          image:
            "https://static.cdn.oskelly.ru/product/1795513/item-f902eba9-c2df-4ad7-b0fe-1aca7213eb32.webp",
          size: "XL",
          publich: true,
          weight: "1700",
          user_id: 1,
          category_id: 2,
          sub_category_id: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "PRADA",
          price: "110000",
          description: "Шикарный костюм Prada.",
          image:
            "https://static.cdn.oskelly.ru/product/1588203/item-b3451c21-acb0-40b3-bf98-72ff4f09347a.jpg.webp",
          size: "S",
          publich: true,
          weight: "900",
          user_id: 1,
          category_id: 2,
          sub_category_id: 7,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "EA7",
          price: "35000",
          description: "Костюм EA7.",
          image:
            "https://static.cdn.oskelly.ru/product/1740101/item-136c11b5-177c-4c1e-8efa-3c1bf321f1d3.webp",
          size: "M",
          publich: true,
          weight: "800",
          user_id: 1,
          category_id: 2,
          sub_category_id: 7,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "BIKEMBERGS",
          price: "44000",
          description:
            "Для путешествий и активного отдыха команда бренда создала горчичный костюм. Брюки удобно садятся за счет эластичного пояса на кулиске и облегающих манжет, а толстовка с капюшоном удобно регулируется молнией.",
          image:
            "https://static.cdn.oskelly.ru/product/1593239/item-e0b40818-05be-4dfe-ae3f-e8c1b5cb0f75.webp",
          size: "M",
          publich: true,
          weight: "800",
          user_id: 1,
          category_id: 2,
          sub_category_id: 7,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "KITON",
          price: "70000",
          description: "Классический костюм Kiton ",
          image:
            "https://static.cdn.oskelly.ru/product/1171398/item-778ec091-72e6-4595-989a-5194df0028b6.jpg.webp",
          size: "XL",
          publich: true,
          weight: "1100",
          user_id: 1,
          category_id: 2,
          sub_category_id: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "MUGLER",
          price: "45000",
          description: "Костюм одевал пару раз. Теплый.",
          image:
            "https://static.cdn.oskelly.ru/product/1492934/item-3910eb45-0a45-449c-aa07-bacdcbd86d59.jpg.webp",
          size: "M",
          publich: true,
          weight: "1300",
          user_id: 1,
          category_id: 2,
          sub_category_id: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "HUGO BOSS",
          price: "130000",
          description: "новый очень тонкая шерсть .",
          image:
            "https://static.cdn.oskelly.ru/product/1803755/item-a3aed065-c3f6-434c-81f0-7fea10b9c8a1.jpg.webp",
          size: "L",
          publich: true,
          weight: "900",
          user_id: 1,
          category_id: 2,
          sub_category_id: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "MONSGLER",
          price: "10",
          description:
            "Завязки находятся на внутренней части, внешне штаны выглядят хорошо с чем угодно.",
          image:
            "https://static.cdn.oskelly.ru/product/1500745/item-90f30027-fe54-4554-9447-ca150c23a85d.jpg.webp",
          size: "L",
          publich: true,
          weight: "600",
          user_id: 1,
          category_id: 2,
          sub_category_id: 9,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "CHLOE",
          price: "21000",
          description:
            "Шерстяные брюки от французского модного дома Chloé. Идеальная посадка. Классический силуэт. Слегка укорочения модель",
          image:
            "https://static.cdn.oskelly.ru/product/1511248/item-4a200310-0940-49a0-baae-ec589b7af694.jpg.webp",
          size: "S",
          publich: true,
          weight: "500",
          user_id: 1,
          category_id: 2,
          sub_category_id: 9,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "MARCELO BURLON COUNTY OF MILAN",
          price: "15000",
          description:
            "Фирменный принт в виде распахнутых крыльев подчеркивает линию плеч.",
          image:
            "https://static.cdn.oskelly.ru/product/1266366/item-2312b516-c9b1-4e56-b180-028340dae641.jpg.webp",
          size: "S",
          publich: true,
          weight: "300",
          user_id: 1,
          category_id: 2,
          sub_category_id: 10,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "BALMAIN",
          price: "27000",
          description: "Состояние отличное",
          image:
            "https://static.cdn.oskelly.ru/product/1807690/item-d9ba39f6-f433-463b-a634-75b27f1c5f52.png.webp",
          size: "S",
          publich: true,
          weight: "400",
          user_id: 1,
          category_id: 2,
          sub_category_id: 10,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "CARNELIANI",
          price: "15000",
          description: "Очень приятная футболка",
          image:
            "https://static.cdn.oskelly.ru/product/871259/item-7060aa1f-18de-4564-8b14-a69839cfbf74.jpg.webp",
          size: "M",
          publich: true,
          weight: "500",
          user_id: 1,
          category_id: 2,
          sub_category_id: 10,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "RALPH LAUREN",
          price: "27000",
          description:
            "Платье POLO RALPH LAUREN , купила в ЦУМе ,выходило в люди пару раз.",
          image:
            "https://static.cdn.oskelly.ru/product/1734658/item-cd4e7e0e-5a7d-464b-93b1-b35c1970b305.jpg.webp",
          size: "S",
          publich: true,
          weight: "300",
          user_id: 1,
          category_id: 2,
          sub_category_id: 11,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "MIU MIU",
          price: "38000",
          description:
            "MIU MIU - бренд одежды, известный среди модниц, как утонченный, по-девичьи изящный. Платье данной модели как раз отвечает этим характеристикам",
          image:
            "https://static.cdn.oskelly.ru/product/3046/item-bda38872-71a5-43b2-8929-a4cb4538b53d.webp",
          size: "XS",
          publich: true,
          weight: "300",
          user_id: 1,
          category_id: 2,
          sub_category_id: 11,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Подкатегория 2_7",
          price: "10",
          description: "Фу очки",
          image:
            "https://static.cdn.oskelly.ru/product/1794161/tiny-0ae4fc36-1f65-4791-96d0-fa3fdafc7b0c.jpg.webp",
          size: "26",
          publich: true,
          weight: "100",
          user_id: 1,
          category_id: 2,
          sub_category_id: 12,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Подкатегория 2_7",
          price: "10",
          description: "Фу очки",
          image:
            "https://static.cdn.oskelly.ru/product/1794161/tiny-0ae4fc36-1f65-4791-96d0-fa3fdafc7b0c.jpg.webp",
          size: "26",
          publich: true,
          weight: "100",
          user_id: 1,
          category_id: 2,
          sub_category_id: 12,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Подкатегория 2_8",
          price: "10",
          description: "Фу очки",
          image:
            "https://static.cdn.oskelly.ru/product/1794161/tiny-0ae4fc36-1f65-4791-96d0-fa3fdafc7b0c.jpg.webp",
          size: "26",
          publich: true,
          weight: "100",
          user_id: 1,
          category_id: 2,
          sub_category_id: 13,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Подкатегория 2_9",
          price: "10",
          description: "Фу очки",
          image:
            "https://static.cdn.oskelly.ru/product/1794161/tiny-0ae4fc36-1f65-4791-96d0-fa3fdafc7b0c.jpg.webp",
          size: "26",
          publich: true,
          weight: "100",
          user_id: 1,
          category_id: 2,
          sub_category_id: 14,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Подкатегория 3_1",
          price: "10",
          description: "Фу очки",
          image:
            "https://static.cdn.oskelly.ru/product/1794161/tiny-0ae4fc36-1f65-4791-96d0-fa3fdafc7b0c.jpg.webp",
          size: "26",
          publich: true,
          weight: "100",
          user_id: 1,
          category_id: 3,
          sub_category_id: 15,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Подкатегория 3_1",
          price: "10",
          description: "Фу очки",
          image:
            "https://static.cdn.oskelly.ru/product/1794161/tiny-0ae4fc36-1f65-4791-96d0-fa3fdafc7b0c.jpg.webp",
          size: "26",
          publich: true,
          weight: "100",
          user_id: 1,
          category_id: 3,
          sub_category_id: 16,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Подкатегория 3_2",
          price: "10",
          description: "Фу очки",
          image:
            "https://static.cdn.oskelly.ru/product/1794161/tiny-0ae4fc36-1f65-4791-96d0-fa3fdafc7b0c.jpg.webp",
          size: "26",
          publich: true,
          weight: "100",
          user_id: 1,
          category_id: 3,
          sub_category_id: 17,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Подкатегория 3_3",
          price: "10",
          description: "Фу очки",
          image:
            "https://static.cdn.oskelly.ru/product/1794161/tiny-0ae4fc36-1f65-4791-96d0-fa3fdafc7b0c.jpg.webp",
          size: "26",
          publich: true,
          weight: "100",
          user_id: 1,
          category_id: 3,
          sub_category_id: 18,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Подкатегория 3_4",
          price: "10",
          description: "Фу очки",
          image:
            "https://static.cdn.oskelly.ru/product/1794161/tiny-0ae4fc36-1f65-4791-96d0-fa3fdafc7b0c.jpg.webp",
          size: "26",
          publich: true,
          weight: "100",
          user_id: 1,
          category_id: 3,
          sub_category_id: 19,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Подкатегория 3_5",
          price: "10",
          description: "Фу очки",
          image:
            "https://static.cdn.oskelly.ru/product/1794161/tiny-0ae4fc36-1f65-4791-96d0-fa3fdafc7b0c.jpg.webp",
          size: "26",
          publich: true,
          weight: "100",
          user_id: 1,
          category_id: 3,
          sub_category_id: 20,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Подкатегория 4_1",
          price: "10",
          description: "Фу очки",
          image:
            "https://static.cdn.oskelly.ru/product/1794161/tiny-0ae4fc36-1f65-4791-96d0-fa3fdafc7b0c.jpg.webp",
          size: "26",
          publich: true,
          weight: "100",
          user_id: 1,
          category_id: 4,
          sub_category_id: 21,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Подкатегория 4_2",
          price: "10",
          description: "Фу очки",
          image:
            "https://static.cdn.oskelly.ru/product/1794161/tiny-0ae4fc36-1f65-4791-96d0-fa3fdafc7b0c.jpg.webp",
          size: "26",
          publich: true,
          weight: "100",
          user_id: 1,
          category_id: 4,
          sub_category_id: 22,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Подкатегория 4_3",
          price: "10",
          description: "Фу очки",
          image:
            "https://static.cdn.oskelly.ru/product/1794161/tiny-0ae4fc36-1f65-4791-96d0-fa3fdafc7b0c.jpg.webp",
          size: "26",
          publich: true,
          weight: "100",
          user_id: 1,
          category_id: 4,
          sub_category_id: 23,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Подкатегория 4_4",
          price: "10",
          description: "Фу очки",
          image:
            "https://static.cdn.oskelly.ru/product/1794161/tiny-0ae4fc36-1f65-4791-96d0-fa3fdafc7b0c.jpg.webp",
          size: "26",
          publich: true,
          weight: "100",
          user_id: 1,
          category_id: 4,
          sub_category_id: 24,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Подкатегория 5_1",
          price: "10",
          description: "Фу очки",
          image:
            "https://static.cdn.oskelly.ru/product/1794161/tiny-0ae4fc36-1f65-4791-96d0-fa3fdafc7b0c.jpg.webp",
          size: "26",
          publich: true,
          weight: "100",
          user_id: 1,
          category_id: 5,
          sub_category_id: 25,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Подкатегория 5_2",
          price: "10",
          description: "Фу очки",
          image:
            "https://static.cdn.oskelly.ru/product/1794161/tiny-0ae4fc36-1f65-4791-96d0-fa3fdafc7b0c.jpg.webp",
          size: "26",
          publich: true,
          weight: "100",
          user_id: 1,
          category_id: 5,
          sub_category_id: 26,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Подкатегория 5_3",
          price: "10",
          description: "Фу очки",
          image:
            "https://static.cdn.oskelly.ru/product/1794161/tiny-0ae4fc36-1f65-4791-96d0-fa3fdafc7b0c.jpg.webp",
          size: "26",
          publich: true,
          weight: "100",
          user_id: 1,
          category_id: 5,
          sub_category_id: 27,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Подкатегория 5_4",
          price: "10",
          description: "Фу очки",
          image:
            "https://static.cdn.oskelly.ru/product/1794161/tiny-0ae4fc36-1f65-4791-96d0-fa3fdafc7b0c.jpg.webp",
          size: "26",
          publich: true,
          weight: "100",
          user_id: 1,
          category_id: 5,
          sub_category_id: 28,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Подкатегория 6_1",
          price: "10",
          description: "Фу очки",
          image:
            "https://static.cdn.oskelly.ru/product/1794161/tiny-0ae4fc36-1f65-4791-96d0-fa3fdafc7b0c.jpg.webp",
          size: "26",
          publich: true,
          weight: "100",
          user_id: 1,
          category_id: 6,
          sub_category_id: 29,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Подкатегория 6_2",
          price: "10",
          description: "Фу очки",
          image:
            "https://static.cdn.oskelly.ru/product/1794161/tiny-0ae4fc36-1f65-4791-96d0-fa3fdafc7b0c.jpg.webp",
          size: "26",
          publich: true,
          weight: "100",
          user_id: 1,
          category_id: 6,
          sub_category_id: 30,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      
      ],
      {}
    );
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete("Posts", null, {});
  },
};
